version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn --frozen-lockfile 
            - run: yarn test
workflows:
    test:
      jobs:
        - test