name: Contributors

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Update the contributors list    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: contributors # will run `yarn build` command
    - name: Simple commit
      uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: 'Update contributors list'
